sections:
  personal_info:
    title: "פרטים אישיים"
    fields:
      - name: "שם מלא"
        required: true
      - name: "תעודת זהות"
        required: true
      - name: "כתובת"
        required: true
      - name: "טלפון"
        required: true
      - name: "דואר אלקטרוני"
        required: true

  investment_experience:
    title: "ניסיון בהשקעות"
    questions:
      - text: "האם יש לך ניסיון קודם בשוק ההון?"
        type: "boolean"
      - text: "כמה שנות ניסיון יש לך בהשקעות?"
        type: "number"
      - text: "באילו אפיקי השקעה התנסית?"
        type: "multiple"
        options:
          - "מניות"
          - "אגרות חוב"
          - "קרנות נאמנות"
          - "מוצרים מובנים"
          - "נדל\"ן"
          - "אחר"

  financial_status:
    title: "מצב פיננסי"
    questions:
      - text: "מהו היקף הנכסים הנזילים שלך?"
        type: "range"
        ranges:
          - "עד 500,000 ₪"
          - "500,000-2,000,000 ₪"
          - "2,000,000-5,000,000 ₪"
          - "מעל 5,000,000 ₪"
      - text: "מהי ההכנסה השנתית שלך?"
        type: "range"
        ranges:
          - "עד 300,000 ₪"
          - "300,000-700,000 ₪"
          - "700,000-1,200,000 ₪"
          - "מעל 1,200,000 ₪"

  risk_profile:
    title: "פרופיל סיכון"
    questions:
      - text: "מהי רמת הסיכון המועדפת עליך?"
        type: "single"
        options:
          - "נמוכה - שמירה על הקרן"
          - "בינונית - איזון בין סיכון לתשואה"
          - "גבוהה - מוכנות לסיכון גבוה"
      - text: "מהו אופק ההשקעה המתוכנן?"
        type: "single"
        options:
          - "קצר (עד שנה)"
          - "בינוני (1-3 שנים)"
          - "ארוך (מעל 3 שנים)"

  investment_goals:
    title: "מטרות השקעה"
    questions:
      - text: "מהן מטרות ההשקעה העיקריות שלך?"
        type: "multiple"
        options:
          - "שמירה על הקרן"
          - "הכנסה שוטפת"
          - "צמיחה לטווח ארוך"
          - "חיסכון לפרישה"
          - "אחר"

declarations:
  - text: "הריני מצהיר/ה כי כל המידע שמסרתי הוא נכון ומדויק"
    required: true
  - text: "אני מבין/ה את הסיכונים הכרוכים בהשקעה"
    required: true
  - text: "קראתי והבנתי את תנאי ההסכם"
    required: true
