description: |
  מובנה גלובל היא חברת שיווק השקעות מובילה בעלת רישיון מרשות ניירות ערך.
  אנחנו מתמחים במוצרי Autocallable על מניות מובילות בחו"ל.
  החברה מציעה פתרונות השקעה מתקדמים המשלבים פוטנציאל לתשואה עם הגנה חלקית על הקרן.

contact_info:
  phone: "0544533709"
  email: "info@movne.co.il"
  address: "רעננה"

licenses:
  - "רישיון שיווק השקעות מרשות ניירות ערך"
  - "חבר באיגוד הברוקרים"

specialties:
  - "מוצרי Autocallable"
  - "הגנה חלקית על הקרן"
  - "השקעות במניות מובילות בחו\"ל"
  - "ייעוץ מקצועי מותאם אישית"
