disclaimer: |
  אין לראות במידע המוצג המלצה או ייעוץ להשקעה.
  המידע מוצג למטרות אינפורמטיביות בלבד.
  יש לקרוא את תנאי המוצר המלאים לפני קבלת החלטת השקעה.

qualified_investor:
  criteria:
    - ניסיון מוכח בשוק ההון
    - תיק השקעות בהיקף משמעותי
    - הכנסה שנתית גבוהה
    - הון עצמי משמעותי
  
  thresholds:
    portfolio: 8364177  # מעל 8,364,177 ₪
    income: 1254627    # מעל 1,254,627 ₪ הכנסה שנתית
    combined:
      portfolio: 5227610  # מעל 5,227,610 ₪ נכסים נזילים
      income: 627313     # ו-627,313 ₪ הכנסה שנתית

restricted_info:
  - אחוזי תשואה ספציפיים
  - שיעורי ריבית מדויקים
  - הבטחת רווחים
  - תחזיות ביצועים

compliance:
  - רישיון שיווק השקעות מרשות ניירות ערך
  - עמידה בכל דרישות הרגולציה
  - שקיפות מלאה ללקוח
  - תיעוד מלא של כל פעולה
