description: |
  מוצרי Autocallable המציעים:
  • השקעה בסל של 3-4 מניות איכותיות מחו"ל
  • מנגנון הגנה חכם על קרן ההשקעה
  • תקופת השקעה של עד 3 שנים
  • אפשרות לפדיון מוקדם בתנאים מסוימים

product_types:
  autocallable:
    name: "Autocallable"
    description: "מוצר מובנה המאפשר השקעה במניות מובילות עם מנגנון הגנה"
    features:
      - "הגנה חלקית על הקרן"
      - "אפשרות לפדיון מוקדם"
      - "חשיפה למניות איכותיות"
    min_investment: 100000
    term: "עד 3 שנים"
    protection: "הגנה חלקית על הקרן"

qualification_requirements:
  - "ניסיון בשוק ההון"
  - "תיק השקעות בהיקף משמעותי"
  - "הכנסה שנתית גבוהה"
  - "הון עצמי משמעותי"
