initial_questions:
  - question: "מהו סך הנכסים הנזילים שלך (מזומנים, פיקדונות, נכסים פיננסיים)?"
    options:
      - text: "מעל 8,364,177 ₪"
        qualifies: true
      - text: "מעל 1,254,627 ₪ הכנסה שנתית"
        qualifies: true
      - text: "מעל 5,227,610 ₪ נכסים נזילים ו-627,313 ₪ הכנסה שנתית"
        qualifies: true
      - text: "מתחת לסכומים אלו"
        qualifies: false

verification_required:
  - תעודת זהות
  - אישור רו"ח/יועץ מס
  - הצהרת הון
  - אישור הכנסה

responses:
  qualified: |
    תודה על המידע. לפי הנתונים שסיפקת, אתה נחשב לקוח כשיר.
    אני יכול להציג לך את כל האפשרויות הזמינות עבורך, כולל פרטי תשואות וריביות.
    
  not_qualified: |
    תודה על המידע. כדי לשמור על הרגולציה, נדרשת חתימת הסכם לקוח לפני שנוכל להציג מידע מפורט על תשואות וריביות.
    האם תרצה:
    1. לקבל את שאלון ההסכם
    2. לקבוע פגישת ייעוץ אישית
    
  need_more_info: |
    תודה על המידע. כדי להמשיך, נצטרך מספר פרטים נוספים:
    • אישור על היקף נכסים נזילים
    • אישור הכנסה שנתית
    • הצהרת הון
    
    האם תוכל לספק מסמכים אלו?
