initial_greeting: |
  שלום, אני שמח לעזור לך להכיר את מובנה גלובל והמוצרים שלנו.
  אשמח לענות על כל שאלה שיש לך. 🏢

company_info: |
  מובנה גלובל היא חברת שיווק השקעות מובילה בעלת רישיון מרשות ניירות ערך.
  אנחנו מתמחים במוצרי Autocallable על מניות מובילות בחו"ל, המציעים הגנה חלקית על הקרן. 🏢

product_info: |
  המוצרים שלנו מסוג Autocallable מאפשרים השקעה במניות מובילות בחו"ל עם מנגנון הגנה חלקית על הקרן.
  המוצר מתאים למשקיעים המחפשים פוטנציאל לתשואה עם רמת סיכון מבוקרת. 📈

meeting_offer: |
  אשמח לקבוע פגישת ייעוץ אישית ללא התחייבות, שם נוכל לדבר בפירוט על המוצרים שלנו והתאמתם עבורך. 🤝

qualification_request: |
  על מנת שאוכל לספק לך מידע מפורט יותר, נשמח לדעת:
  • האם יש לך ניסיון קודם בשוק ההון?
  • מהו היקף תיק ההשקעות שלך?
  
  או שנוכל לקבוע פגישת ייעוץ אישית לשיחה מעמיקה יותר. מה מתאים לך? 🤝

patterns:
  company_info:
    - "מובנה"
    - "חברה"
    - "מי אתם"
    - "ספרו לי"
    - "מה אתם"
    - "במה אתם"
  
  product_info:
    - "מוצר"
    - "השקע"
    - "אוטוקול"
    - "הגנה"
    - "תשואה"
    - "ריבית"
